export interface EngineeringRecipe {
  id: string
  name: string
  levelRequired: number
  xpReward: number
  icon?: string
  image?: string // Image path for the recipe (e.g., '/images/engineering/dagger.png')
  description: string
  ingredients: {
    resourceId: string // This will be the placeholder metal ID
    amount: number
  }[]
  time: number // Time in seconds to craft
  value: number // Sell value of the crafted item
  // Equipment stats (only for equippable items)
  equipmentStats?: {
    attackType: 'bash' | 'cut' | 'block' | 'stab' // Preferred attack type for this item
    attackScale: number // Multiplier for XP when using preferred attack type (e.g., 1.5x)
    damage?: number // Attack damage (for weapons)
    armor?: number // Armor value (for armor pieces)
    armorStyle?: 'melee' | 'ranged' | 'magic' | 'hybrid' // Armor style class (determines affinity)
    accuracy?: number // Accuracy rating (a in hit chance formula)
    critChance?: number // Base crit chance bonus
    armorType?: 'plate' | 'leather' | 'cloth' | 'hybrid' // Determines mitigation behaviour
    damageReductionPercent?: number // Percent damage reduction provided by the armor
    accuracyPercent?: number // Percent accuracy bonus (for accessories like rings)
  }
}

export const ENGINEERING_RECIPES: EngineeringRecipe[] = [
  // Tier 1 - Placeholder Metal 1
  {
    id: 'Ferrite Dagger',
    name: 'Ferrite Dagger',
    levelRequired: 1,
    xpReward: 10,
    image: '/images/engineering/dagger1.png',
    description: 'Basic combat dagger',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 1 }],
    time: 3,
    value: 99,
    equipmentStats: {
      attackType: 'stab',
      attackScale: 1.5,
      damage: 20,
      accuracy: 2,
      critChance: 3,
    },
  },
  {
    id: 'ferrite-casings',
    name: 'Ferrite Casings',
    levelRequired: 1,
    xpReward: 10,
    image: '/images/engineering/ferrite_casings.png',
    description: 'Bullet casings for simple ammo production',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 15 }],
    time: 5,
    value: 1485,
  },
  {
    id: 'ferrite-gloves',
    name: 'Ferrite Gloves',
    levelRequired: 5,
    xpReward: 20,
    image: '/images/engineering/ferrite_gloves.png',
    description: 'Calibrated ring that improves targeting focus',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 2 }],
    time: 5,
    value: 198,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.0,
      armor: 2,
  },},
  {
    id: 'ferrite-sword',
    name: 'Ferrite Sword',
    levelRequired: 7,
    xpReward: 10,
    image: '/images/engineering/ferrite_sword.png',
    description: 'Standard combat sword',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 1 }],
    time: 4,
    value: 99,
    equipmentStats: {
      attackType: 'stab',
      attackScale: 1.5,
      damage: 25,
      accuracy: 3,
      critChance: 4,
    },
  },
  {
    id: 'ferrite-ring',
    name: 'Ferrite Ring',
    levelRequired: 9,
    xpReward: 20,
    image: '/images/engineering/ferrite_ring.png',
    description: 'Protective hand armor',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 2 }],
    time: 5,
    value: 198,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.0,
      accuracyPercent: 5,
    },
  },
  {
    id: 'ferrite-axe',
    name: 'Ferrite Axe',
    levelRequired: 10,
    xpReward: 20,
    image: '/images/engineering/ferrite_axe.png',
    description: 'Curved blade weapon',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 2 }],
    time: 5,
    value: 198,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 30,
      accuracy: 4,
      critChance: 5,
    },
  },
  {
    id: 'ferrite-helmet',
    name: 'Ferrite Helmet',
    levelRequired: 12,
    xpReward: 20,
    image: '/images/engineering/ferrite_helmet.png',
    description: 'Head protection',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 2 }],
    time: 6,
    value: 198,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.0,
      armor: 3,
    },
  },
  {
    id: 'ferrite-shield',
    name: 'Ferrite Shield',
    levelRequired: 13,
    xpReward: 20,
    image: '/images/engineering/ferrite_shield.png',
    description: 'Javelin tips',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 5 }],
    time: 6,
    value: 495,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.5,
      damage: 35,
      accuracy: 2,
      critChance: 3,
    },
  },
  {
    id: 'ferrite-boots',
    name: 'Ferrite Boots',
    levelRequired: 15,
    xpReward: 30,
    image: '/images/engineering/ferrite_boots.png',
    description: 'Foot armor',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 3 }],
    time: 7,
    value: 297,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.0,
      armor: 2,
    },
  },
  {
    id: 'ferrite-leggings',
    name: 'Ferrite Leggings',
    levelRequired: 17,
    xpReward: 30,
    image: '/images/engineering/ferrite_legs.png',
    description: 'Defensive shield',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 3 }],
    time: 8,
    value: 297,
    equipmentStats: {
      attackType: 'block',
      attackScale: 1.5,
      armor: 5,
    },
  },
  {
    id: 'ferrite-morningstar',
    name: 'Ferrite Morningstar',
    levelRequired: 19,
    xpReward: 30,
    image: '/images/engineering/ferrite_morningstar.png',
    description: 'Heavy melee weapon',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 3 }],
    time: 7,
    value: 297,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.5,
      damage: 35,
      accuracy: 2,
      critChance: 3,
    },
  },
  {
    id: 'ferrite-armor',
    name: 'Ferrite Armor',
    levelRequired: 15,
    xpReward: 30,
    image: '/images/engineering/ferrite_armor.png',
    description: 'Standard ferrite plate armor offering solid protection',
    ingredients: [{ resourceId: 'ferrite-ingot', amount: 3 }],
    time: 10,
    value: 1980,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.0,
      armor: 8,
      armorStyle: 'melee',
      armorType: 'plate',
      damageReductionPercent: 6,
    },
  },
  
  // Tier 2 - Placeholder Metal 2
  {
    id: 'industrial-dagger',
    name: 'Industrial Dagger',
    levelRequired: 21,
    xpReward: 10,
    image: '/images/engineering/industrial_dagger.png',
    description: 'Basic combat dagger',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 1 }],
    time: 3,
    value: 99,
    equipmentStats: {
      attackType: 'stab',
      attackScale: 1.5,
      damage: 20,
      accuracy: 2,
      critChance: 3,
    },
  },
  {
    id: 'industrial-casings',
    name: 'Industrial Casings',
    levelRequired: 1,
    xpReward: 10,
    image: '/images/engineering/industrial_casings.png',
    description: 'Bullet casings for simple ammo production',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 15 }],
    time: 5,
    value: 1485,
  },
  {
    id: 'industrial-gloves',
    name: 'Industrial Gloves',
    levelRequired: 5,
    xpReward: 20,
    image: '/images/engineering/industrial_gloves.png',
    description: 'Protective hand armor',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 2 }],
    time: 5,
    value: 198,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.0,
      armor: 2,
  },},
  {
    id: 'industrial-sword',
    name: 'Industrial Sword',
    levelRequired: 7,
    xpReward: 10,
    image: '/images/engineering/industrial_sword.png',
    description: 'Standard combat sword',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 1 }],
    time: 4,
    value: 99,
    equipmentStats: {
      attackType: 'stab',
      attackScale: 1.5,
      damage: 25,
      accuracy: 3,
      critChance: 4,
    },
  },
  {
    id: 'industrial-ring',
    name: 'Industrial Ring',
    levelRequired: 9,
    xpReward: 20,
    image: '/images/engineering/industrial_ring.png',
    description: 'Protective hand armor',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 2 }],
    time: 5,
    value: 198,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.0,
      armor: 2,
    },
  },
  {
    id: 'industrial-axe',
    name: 'Industrial Axe',
    levelRequired: 10,
    xpReward: 20,
    image: '/images/engineering/industrial_axe.png',
    description: 'Curved blade weapon',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 2 }],
    time: 5,
    value: 198,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 30,
      accuracy: 4,
      critChance: 5,
    },
  },
  {
    id: 'industrial-helmet',
    name: 'Industrial Helmet',
    levelRequired: 12,
    xpReward: 20,
    image: '/images/engineering/industrial_helmet.png',
    description: 'Head protection',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 2 }],
    time: 6,
    value: 198,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.0,
      armor: 3,
    },
  },
  {
    id: 'industrial-shield',
    name: 'Industrial Shield',
    levelRequired: 13,
    xpReward: 20,
    image: '/images/engineering/industrial_shield.png',
    description: 'Javelin tips',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 5 }],
    time: 6,
    value: 495,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.5,
      damage: 35,
      accuracy: 2,
      critChance: 3,
    },
  },
  {
    id: 'industrial-boots',
    name: 'Industrial Boots',
    levelRequired: 15,
    xpReward: 30,
    image: '/images/engineering/industrial_boots.png',
    description: 'Foot armor',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 3 }],
    time: 7,
    value: 297,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.0,
      armor: 2,
    },
  },
  {
    id: 'industrial-leggings',
    name: 'Industrial Leggings',
    levelRequired: 17,
    xpReward: 30,
    image: '/images/engineering/industrial_legs.png',
    description: 'Defensive shield',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 3 }],
    time: 8,
    value: 297,
    equipmentStats: {
      attackType: 'block',
      attackScale: 1.5,
      armor: 5,
    },
  },
  {
    id: 'industrial-morningstar',
    name: 'Industrial Morningstar',
    levelRequired: 19,
    xpReward: 30,
    image: '/images/engineering/industrial_morningstar.png',
    description: 'Heavy melee weapon',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 3 }],
    time: 7,
    value: 297,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.5,
      damage: 35,
      accuracy: 2,
      critChance: 3,
    },
  },
  {
    id: 'industrial-armor',
    name: 'Industrial Armor',
    levelRequired: 15,
    xpReward: 30,
    image: '/images/engineering/industrial_armor.png',
    description: 'Crossbow mechanism',
    ingredients: [{ resourceId: 'industrial-ingot', amount: 3 }],
    time: 10,
    value: 1980,
  },
    
  // Tier 3 - Placeholder Metal 3
  {
    id: 'placeholder-metal-3-craft',
    name: 'Placeholder Metal 3',
    levelRequired: 40,
    xpReward: 30,
    icon: '⚙️',
    description: 'Hardened metal alloy',
    ingredients: [{ resourceId: 'placeholder-metal-2', amount: 1 }],
    time: 5,
    value: 990,
  },
  {
    id: 'placeholder-dagger-3',
    name: 'Placeholder Dagger 3',
    levelRequired: 25,
    xpReward: 30,
    icon: '🗡️',
    description: 'Masterwork combat dagger',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 1 }],
    time: 5,
    value: 990,
    equipmentStats: {
      attackType: 'stab',
      attackScale: 1.5,
      damage: 70,
      accuracy: 4,
      critChance: 5,
    },
  },
  {
    id: 'placeholder-throwing-knife-3',
    name: 'Placeholder Throwing Knife 3',
    levelRequired: 26,
    xpReward: 30,
    icon: '🔪',
    description: 'Masterwork throwing weapon',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 4 }],
    time: 6,
    value: 396,
  },
  {
    id: 'placeholder-sword-3',
    name: 'Placeholder Sword 3',
    levelRequired: 27,
    xpReward: 30,
    icon: '⚔️',
    description: 'Masterwork combat sword',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 1 }],
    time: 6,
    value: 990,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 75,
      accuracy: 3,
      critChance: 4,
    },
  },
  {
    id: 'placeholder-arrowtips-3',
    name: 'Placeholder Arrowtips 3',
    levelRequired: 28,
    xpReward: 30,
    icon: '➶',
    description: 'Masterwork arrow tips',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 15 }],
    time: 8,
    value: 1485,
  },
  {
    id: 'placeholder-gloves-3',
    name: 'Placeholder Gloves 3',
    levelRequired: 29,
    xpReward: 60,
    icon: '🧤',
    description: 'Masterwork hand armor',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 2 }],
    time: 7,
    value: 1584,
  },
  {
    id: 'placeholder-scimitar-3',
    name: 'Placeholder Scimitar 3',
    levelRequired: 30,
    xpReward: 60,
    icon: '🔱',
    description: 'Masterwork curved blade',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 2 }],
    time: 7,
    value: 1584,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 80,
      accuracy: 4,
      critChance: 5,
    },
  },
  {
    id: 'placeholder-helmet-3',
    name: 'Placeholder Helmet 3',
    levelRequired: 31,
    xpReward: 60,
    icon: '🪖',
    description: 'Masterwork head protection',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 2 }],
    time: 8,
    value: 1584,
  },
  {
    id: 'placeholder-battleaxe-3',
    name: 'Placeholder Battleaxe 3',
    levelRequired: 32,
    xpReward: 90,
    icon: '🪓',
    description: 'Masterwork melee weapon',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 3 }],
    time: 9,
    value: 2475,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.5,
      damage: 85,
      accuracy: 2,
      critChance: 3,
    },
  },
  {
    id: 'placeholder-javelin-heads-3',
    name: 'Placeholder Javelin Heads 3',
    levelRequired: 33,
    xpReward: 60,
    icon: '🏹',
    description: 'Masterwork javelin tips',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 5 }],
    time: 8,
    value: 1980,
  },
  {
    id: 'placeholder-boots-3',
    name: 'Placeholder Boots 3',
    levelRequired: 34,
    xpReward: 60,
    icon: '👢',
    description: 'Masterwork foot armor',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 2 }],
    time: 8,
    value: 1584,
  },
  {
    id: 'placeholder-shield-3',
    name: 'Placeholder Shield 3',
    levelRequired: 36,
    xpReward: 90,
    icon: '🛡️',
    description: 'Masterwork defensive shield',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 3 }],
    time: 10,
    value: 2475,
  },
  {
    id: 'placeholder-2h-sword-3',
    name: 'Placeholder 2H Sword 3',
    levelRequired: 38,
    xpReward: 90,
    icon: '⚔️',
    description: 'Masterwork two-handed sword',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 3 }],
    time: 11,
    value: 2475,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 90,
      accuracy: 5,
      critChance: 6,
    },
  },
  {
    id: 'placeholder-crossbow-head-3',
    name: 'Placeholder Crossbow Head 3',
    levelRequired: 39,
    xpReward: 90,
    icon: '🏹',
    description: 'Masterwork crossbow mechanism',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 3 }],
    time: 12,
    value: 5940,
  },
  {
    id: 'placeholder-platelegs-3',
    name: 'Placeholder Platelegs 3',
    levelRequired: 40,
    xpReward: 90,
    icon: '🦵',
    description: 'Masterwork leg armor',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 3 }],
    time: 11,
    value: 2475,
  },
  {
    id: 'placeholder-platebody-3',
    name: 'Placeholder Platebody 3',
    levelRequired: 42,
    xpReward: 150,
    icon: '🛡️',
    description: 'Masterwork chest armor',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 5 }],
    time: 14,
    value: 4455,
  },
  
  // Tier 4 - Placeholder Metal 4
  {
    id: 'placeholder-metal-4-craft',
    name: 'Placeholder Metal 4',
    levelRequired: 60,
    xpReward: 50,
    icon: '⚙️',
    description: 'Elite smelted metal',
    ingredients: [{ resourceId: 'placeholder-metal-3', amount: 1 }],
    time: 6,
    value: 5940,
  },
  {
    id: 'placeholder-dagger-4',
    name: 'Placeholder Dagger 4',
    levelRequired: 40,
    xpReward: 50,
    icon: '🗡️',
    description: 'Elite combat dagger',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 1 }],
    time: 6,
    value: 5940,
    equipmentStats: {
      attackType: 'stab',
      attackScale: 1.5,
      damage: 80,
      accuracy: 5,
      critChance: 6,
    },
  },
  {
    id: 'placeholder-throwing-knife-4',
    name: 'Placeholder Throwing Knife 4',
    levelRequired: 41,
    xpReward: 50,
    icon: '🔪',
    description: 'Elite throwing weapon',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 4 }],
    time: 7,
    value: 5940,
  },
  {
    id: 'placeholder-sword-4',
    name: 'Placeholder Sword 4',
    levelRequired: 42,
    xpReward: 50,
    icon: '⚔️',
    description: 'Elite combat sword',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 1 }],
    time: 7,
    value: 5940,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 100,
      accuracy: 3,
      critChance: 4,
    },
  },
  {
    id: 'placeholder-arrowtips-4',
    name: 'Placeholder Arrowtips 4',
    levelRequired: 43,
    xpReward: 50,
    icon: '➶',
    description: 'Elite arrow tips',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 15 }],
    time: 9,
    value: 8910,
  },
  {
    id: 'placeholder-gloves-4',
    name: 'Placeholder Gloves 4',
    levelRequired: 44,
    xpReward: 100,
    icon: '🧤',
    description: 'Elite hand armor',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 2 }],
    time: 8,
    value: 11880,
  },
  {
    id: 'placeholder-scimitar-4',
    name: 'Placeholder Scimitar 4',
    levelRequired: 45,
    xpReward: 100,
    icon: '🔱',
    description: 'Elite curved blade',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 2 }],
    time: 8,
    value: 11880,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 105,
      accuracy: 4,
      critChance: 5,
    },
  },
  {
    id: 'placeholder-helmet-4',
    name: 'Placeholder Helmet 4',
    levelRequired: 46,
    xpReward: 100,
    icon: '🪖',
    description: 'Elite head protection',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 2 }],
    time: 9,
    value: 11880,
  },
  {
    id: 'placeholder-battleaxe-4',
    name: 'Placeholder Battleaxe 4',
    levelRequired: 47,
    xpReward: 150,
    icon: '🪓',
    description: 'Elite melee weapon',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 3 }],
    time: 10,
    value: 17820,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.5,
      damage: 110,
      accuracy: 2,
      critChance: 3,
    },
  },
  {
    id: 'placeholder-javelin-heads-4',
    name: 'Placeholder Javelin Heads 4',
    levelRequired: 48,
    xpReward: 100,
    icon: '🏹',
    description: 'Elite javelin tips',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 5 }],
    time: 9,
    value: 14850,
  },
  {
    id: 'placeholder-boots-4',
    name: 'Placeholder Boots 4',
    levelRequired: 49,
    xpReward: 100,
    icon: '👢',
    description: 'Elite foot armor',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 2 }],
    time: 9,
    value: 14850,
  },
  {
    id: 'placeholder-shield-4',
    name: 'Placeholder Shield 4',
    levelRequired: 51,
    xpReward: 150,
    icon: '🛡️',
    description: 'Elite defensive shield',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 3 }],
    time: 11,
    value: 14850,
  },
  {
    id: 'placeholder-2h-sword-4',
    name: 'Placeholder 2H Sword 4',
    levelRequired: 53,
    xpReward: 150,
    icon: '⚔️',
    description: 'Elite two-handed sword',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 3 }],
    time: 12,
    value: 17820,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 115,
      accuracy: 5,
      critChance: 6,
    },
  },
  {
    id: 'placeholder-crossbow-head-4',
    name: 'Placeholder Crossbow Head 4',
    levelRequired: 54,
    xpReward: 150,
    icon: '🏹',
    description: 'Elite crossbow mechanism',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 3 }],
    time: 13,
    value: 35640,
  },
  {
    id: 'placeholder-platelegs-4',
    name: 'Placeholder Platelegs 4',
    levelRequired: 55,
    xpReward: 150,
    icon: '🦵',
    description: 'Elite leg armor',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 3 }],
    time: 12,
    value: 17820,
  },
  {
    id: 'placeholder-platebody-4',
    name: 'Placeholder Platebody 4',
    levelRequired: 57,
    xpReward: 250,
    icon: '🛡️',
    description: 'Elite chest armor',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 5 }],
    time: 15,
    value: 29700,
  },
  
  // Tier 5 - Placeholder Metal 5
  {
    id: 'placeholder-metal-5-craft',
    name: 'Placeholder Metal 5',
    levelRequired: 70,
    xpReward: 60,
    icon: '⚙️',
    description: 'Legendary smelted metal',
    ingredients: [{ resourceId: 'placeholder-metal-4', amount: 1 }],
    time: 7,
    value: 7920,
  },
  {
    id: 'placeholder-dagger-5',
    name: 'Placeholder Dagger 5',
    levelRequired: 55,
    xpReward: 60,
    icon: '🗡️',
    description: 'Legendary combat dagger',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 1 }],
    time: 7,
    value: 7920,
    equipmentStats: {
      attackType: 'stab',
      attackScale: 1.5,
      damage: 95,
      accuracy: 6,
      critChance: 7,
    },
  },
  {
    id: 'placeholder-throwing-knife-5',
    name: 'Placeholder Throwing Knife 5',
    levelRequired: 56,
    xpReward: 60,
    icon: '🔪',
    description: 'Legendary throwing weapon',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 4 }],
    time: 8,
    value: 7920,
  },
  {
    id: 'placeholder-sword-5',
    name: 'Placeholder Sword 5',
    levelRequired: 57,
    xpReward: 60,
    icon: '⚔️',
    description: 'Legendary combat sword',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 1 }],
    time: 8,
    value: 7920,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 120,
      accuracy: 3,
      critChance: 4,
    },
  },
  {
    id: 'placeholder-arrowtips-5',
    name: 'Placeholder Arrowtips 5',
    levelRequired: 58,
    xpReward: 60,
    icon: '➶',
    description: 'Legendary arrow tips',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 15 }],
    time: 10,
    value: 11880,
  },
  {
    id: 'placeholder-gloves-5',
    name: 'Placeholder Gloves 5',
    levelRequired: 59,
    xpReward: 120,
    icon: '🧤',
    description: 'Legendary hand armor',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 2 }],
    time: 9,
    value: 14850,
  },
  {
    id: 'placeholder-scimitar-5',
    name: 'Placeholder Scimitar 5',
    levelRequired: 60,
    xpReward: 120,
    icon: '🔱',
    description: 'Legendary curved blade',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 2 }],
    time: 9,
    value: 14850,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 125,
      accuracy: 4,
      critChance: 5,
    },
  },
  {
    id: 'placeholder-helmet-5',
    name: 'Placeholder Helmet 5',
    levelRequired: 61,
    xpReward: 120,
    icon: '🪖',
    description: 'Legendary head protection',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 2 }],
    time: 10,
    value: 14850,
  },
  {
    id: 'placeholder-battleaxe-5',
    name: 'Placeholder Battleaxe 5',
    levelRequired: 62,
    xpReward: 180,
    icon: '🪓',
    description: 'Legendary melee weapon',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 3 }],
    time: 11,
    value: 23760,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.5,
      damage: 130,
      accuracy: 2,
      critChance: 3,
    },
  },
  {
    id: 'placeholder-javelin-heads-5',
    name: 'Placeholder Javelin Heads 5',
    levelRequired: 63,
    xpReward: 120,
    icon: '🏹',
    description: 'Legendary javelin tips',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 5 }],
    time: 10,
    value: 14850,
  },
  {
    id: 'placeholder-boots-5',
    name: 'Placeholder Boots 5',
    levelRequired: 64,
    xpReward: 120,
    icon: '👢',
    description: 'Legendary foot armor',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 2 }],
    time: 10,
    value: 14850,
  },
  {
    id: 'placeholder-shield-5',
    name: 'Placeholder Shield 5',
    levelRequired: 66,
    xpReward: 180,
    icon: '🛡️',
    description: 'Legendary defensive shield',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 3 }],
    time: 12,
    value: 17820,
  },
  {
    id: 'placeholder-2h-sword-5',
    name: 'Placeholder 2H Sword 5',
    levelRequired: 68,
    xpReward: 180,
    icon: '⚔️',
    description: 'Legendary two-handed sword',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 3 }],
    time: 13,
    value: 23760,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 135,
      accuracy: 5,
      critChance: 6,
    },
  },
  {
    id: 'placeholder-crossbow-head-5',
    name: 'Placeholder Crossbow Head 5',
    levelRequired: 69,
    xpReward: 180,
    icon: '🏹',
    description: 'Legendary crossbow mechanism',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 3 }],
    time: 14,
    value: 54450,
  },
  {
    id: 'placeholder-platelegs-5',
    name: 'Placeholder Platelegs 5',
    levelRequired: 70,
    xpReward: 180,
    icon: '🦵',
    description: 'Legendary leg armor',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 3 }],
    time: 13,
    value: 23760,
  },
  {
    id: 'placeholder-platebody-5',
    name: 'Placeholder Platebody 5',
    levelRequired: 72,
    xpReward: 300,
    icon: '🛡️',
    description: 'Legendary chest armor',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 5 }],
    time: 16,
    value: 39600,
  },
  
  // Tier 6 - Placeholder Metal 6
  {
    id: 'placeholder-metal-6-craft',
    name: 'Placeholder Metal 6',
    levelRequired: 90,
    xpReward: 75,
    icon: '⚙️',
    description: 'Mythical smelted metal',
    ingredients: [{ resourceId: 'placeholder-metal-5', amount: 1 }],
    time: 8,
    value: 74250,
  },
  {
    id: 'placeholder-dagger-6',
    name: 'Placeholder Dagger 6',
    levelRequired: 70,
    xpReward: 75,
    icon: '🗡️',
    description: 'Mythical combat dagger',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 1 }],
    time: 8,
    value: 74250,
    equipmentStats: {
      attackType: 'stab',
      attackScale: 1.5,
      damage: 110,
      accuracy: 7,
      critChance: 8,
    },
  },
  {
    id: 'placeholder-throwing-knife-6',
    name: 'Placeholder Throwing Knife 6',
    levelRequired: 71,
    xpReward: 75,
    icon: '🔪',
    description: 'Mythical throwing weapon',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 4 }],
    time: 9,
    value: 5940,
  },
  {
    id: 'placeholder-sword-6',
    name: 'Placeholder Sword 6',
    levelRequired: 72,
    xpReward: 75,
    icon: '⚔️',
    description: 'Mythical combat sword',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 1 }],
    time: 9,
    value: 74250,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 140,
      accuracy: 3,
      critChance: 4,
    },
  },
  {
    id: 'placeholder-arrowtips-6',
    name: 'Placeholder Arrowtips 6',
    levelRequired: 73,
    xpReward: 75,
    icon: '➶',
    description: 'Mythical arrow tips',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 15 }],
    time: 11,
    value: 11175,
  },
  {
    id: 'placeholder-gloves-6',
    name: 'Placeholder Gloves 6',
    levelRequired: 74,
    xpReward: 150,
    icon: '🧤',
    description: 'Mythical hand armor',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 2 }],
    time: 10,
    value: 23760,
  },
  {
    id: 'placeholder-scimitar-6',
    name: 'Placeholder Scimitar 6',
    levelRequired: 75,
    xpReward: 150,
    icon: '🔱',
    description: 'Mythical curved blade',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 2 }],
    time: 10,
    value: 23760,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 145,
      accuracy: 4,
      critChance: 5,
    },
  },
  {
    id: 'placeholder-helmet-6',
    name: 'Placeholder Helmet 6',
    levelRequired: 76,
    xpReward: 150,
    icon: '🪖',
    description: 'Mythical head protection',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 2 }],
    time: 11,
    value: 23760,
  },
  {
    id: 'placeholder-battleaxe-6',
    name: 'Placeholder Battleaxe 6',
    levelRequired: 77,
    xpReward: 225,
    icon: '🪓',
    description: 'Mythical melee weapon',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 3 }],
    time: 12,
    value: 39600,
    equipmentStats: {
      attackType: 'bash',
      attackScale: 1.5,
      damage: 150,
      accuracy: 2,
      critChance: 3,
    },
  },
  {
    id: 'placeholder-javelin-heads-6',
    name: 'Placeholder Javelin Heads 6',
    levelRequired: 78,
    xpReward: 150,
    icon: '🏹',
    description: 'Mythical javelin tips',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 5 }],
    time: 11,
    value: 29700,
  },
  {
    id: 'placeholder-boots-6',
    name: 'Placeholder Boots 6',
    levelRequired: 79,
    xpReward: 200,
    icon: '👢',
    description: 'Mythical foot armor',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 2 }],
    time: 11,
    value: 23760,
  },
  {
    id: 'placeholder-shield-6',
    name: 'Placeholder Shield 6',
    levelRequired: 81,
    xpReward: 225,
    icon: '🛡️',
    description: 'Mythical defensive shield',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 3 }],
    time: 13,
    value: 8910,
  },
  {
    id: 'placeholder-2h-sword-6',
    name: 'Placeholder 2H Sword 6',
    levelRequired: 83,
    xpReward: 225,
    icon: '⚔️',
    description: 'Mythical two-handed sword',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 3 }],
    time: 14,
    value: 39600,
    equipmentStats: {
      attackType: 'cut',
      attackScale: 1.5,
      damage: 155,
      accuracy: 5,
      critChance: 6,
    },
  },
  {
    id: 'placeholder-crossbow-head-6',
    name: 'Placeholder Crossbow Head 6',
    levelRequired: 84,
    xpReward: 225,
    icon: '🏹',
    description: 'Mythical crossbow mechanism',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 3 }],
    time: 15,
    value: 69300,
  },
  {
    id: 'placeholder-platelegs-6',
    name: 'Placeholder Platelegs 6',
    levelRequired: 85,
    xpReward: 225,
    icon: '🦵',
    description: 'Mythical leg armor',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 3 }],
    time: 14,
    value: 43659,
  },
  {
    id: 'placeholder-platebody-6',
    name: 'Placeholder Platebody 6',
    levelRequired: 87,
    xpReward: 375,
    icon: '🛡️',
    description: 'Mythical chest armor',
    ingredients: [{ resourceId: 'placeholder-metal-6', amount: 5 }],
    time: 17,
    value: 69300,
  },
]

